### PR TITLE
Dev/cov2 mpire sf

### PR DESCRIPTION
**Pull request by stephan-fuchs**
I solved all merge conflicts between my versions and yours.

### CODE REVIEW

**Comment by matthuska** [comment]
It looks like there are some unnecessary files in the commit, give me some time to go through this and trim out what shouldn't be there.

**Comment by stephan-fuchs** [comment]
> It looks like there are some unnecessary files in the commit, give me some time to go through this and trim out what shouldn't be there.

There were some libraries copied to the root dir, I don't know why. However, I removed those and pushed a cleaner version.

**Comment by matthuska** [comment]
I'll go through the commit today sometime. I think @silenus092 trusts me to do the merge, he can check the changes tomorrow.

**Comment by matthuska** [comment]
I'm going to push a few small changes to this branch. The *.old files shouldn't live in the repo anymore, if someone needs them they can use the git history. We'll also need to do some surgery to the repo to remove those huge library files that were imported, they shouldn't be in the history and they make checking out the repository slow, but I need to figure out a nice way to do that. I deleted the Lineages.py file because @silenus092 said it's not needed anymore, moved the conftest.py file back to tests/ where it belongs, and fixed a bunch of permissions stuff (the .py files don't need to be executable).

There are also some unused files in the repo, can they be deleted? This includes:

- src/covsonar/data/doctest_b117.*
- src/covsonar/data/ref.{fna,gff3} (ref.gb is used)

Lastly the new code seems to leave (empty) "import.log" files around wherever you are running the code from. This should be made an option (e.g. --import-log=import.log) with the default to not create this file at all.

**Comment by matthuska** [comment]
Looks okay to me now. @silenus092 if you also approve merging this branch, please "Squash and merge" this (not just "Merge this branch") and then delete the branch, which should remove the huge files that were accidentally added to this branch from the repository. At that point @stephan-fuchs you can do any further work on a new branch.

**Comment by silenus092** [comment]
@matthuska, great👨‍🚀 Thank you for your help. 

@stephan-fuchs  🧑‍🔧 Thanks, I will merge this PR.

**Comment by matthuska** [comment]
"Squash and merge" don't just "merge" please!!

**Comment by silenus092** [comment]
wait!  I selected the squash and merge button before merging, oh crap me

**Pull request merged**
